# Site settings
title: La Gioconda Sad
description: La Gioconda Sad
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joaquingx.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: La Gioconda Sad
user_description: Major Goblin
user_title: by Joaquin Garmendia
email: joaquin.garmendia@ucsp.edu.pe
twitter_username: joaquingx
github_username:  joaquingx
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
